version: '3.8'

services:
    spring-db:
        container_name: spring-db
        image: postgres:12-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: spring-db
            POSTGRES_USER: spring-db
            POSTGRES_PASSWORD: 123456

    spring-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - spring-db